scheduler:
    device: 'cuda'
    resume: null # resume path
    start_epoch: 0
    epochs: 200
    save_path: './ckpt'

    lr: 1e-4 
    lr_backbone: 1e-5
    batch_size: 2
    weight_decay: 1e-4
    lr_drop: 200
    clip_max_norm: 0.1

model:
    segmentation: true
    num_classes: 13
    backbone:
        ckpt_path: null  # if set, only train mask head
        name: 'resnet50'
        dilation: true
        position_embedding: 'learned' # sine, learned
    Transformer:
        enc_layer: 6
        dec_layer: 6
        aux_loss: false
        dim_feedfoward: 2048
        hidden_dim: 256
        dropout: 0.1
        nhead: 8
        num_queries: 100
        pre_norm: false

no_aux_loss: true

matcher:
    set_cost_class: 1
    set_cost_bbox: 5
    set_cost_giou: 2

loss_coefficient:
    mask_loss_coef: 1
    dice_loss_coef: 1
    bbox_loss_coef: 5
    giou_loss_coef: 2
    eos_coef: 0.1